FROM ubuntu

EXPOSE 8080

WORKDIR /usr/src/app

COPY . .

RUN apt update

RUN apt upgrade -y

RUN apt install -y curl

RUN curl https://dl.google.com/go/go1.16.15.linux-amd64.tar.gz -o ./go1.16.15.linux-amd64.tar.gz

RUN tar -C /usr/local -xzf go1.16.15.linux-amd64.tar.gz

ENV PATH=$PATH:/usr/local/go/bin

RUN go build 

CMD ./server